### ISSUE TITLE
Loading metadata from old files

### ISSUE THREAD

**Issue by tjalb** [paulscherrerinstitute/sf_datafiles#12]
The meta method only loads metadata from the "general" group. Previously this group was named "meta". How can metadata be accessed if the file was created with a previous version of sfdata?

**Comment by NichtJens** [comment]
Ah! That's a good point. I should add backwards compatibility here.

For now, you can work around the problem like this:

```python
from sfdata.sfmeta import get_meta

f = SFDataFiles(...)
f.meta = get_meta(f.file)
```

Can you try that for now please?

**Comment by tjalb** [comment]
This does not work directly. It has to be something like
`f.meta = get_meta(f.files[0].file)`
which has the drawback that I need to know at which position the file with the metadata is. This is not necessarily the case. But ok, I can work around this...

**Comment by NichtJens** [comment]
Then, your `f` is an `SFDataFiles` (plural). I meant an `SFDataFile` (singular).
`.files[0]` is indeed the equivalent of `.file` in my example.

If you want it for a plural one, you need something slightly less simple:

```python
from sfdata.sfmeta import get_meta, SFMeta

fs = SFDataFiles(...)

meta = {}
for f in fs.files:
    m = get_meta(f.file)
    f.meta = m
    meta.update(m or {})
if meta:
    fs.meta = SFMeta(meta)
```

(Not tried this, but I should be roughly correct ;)

**Comment by NichtJens** [comment]
I made some changes (88672faab0d8ff537e96e2c56195b34c12d72a6e / v0.3.2) which make it easy to change the name.

You'd just do this first thing:
```python
import sfdata
sfdata.sfdatafile.NAME_FILE_META = "meta"
```

I am not sure whether I should add an automatic fallback. I would like to avoid people creating new files with the old structure.

From your perspective, is the above "good enough"?

**Comment by tjalb** [comment]
I think that's "good enough". Thank you!

**Comment by NichtJens** [comment]
Great :) Thanks for the feedback!
